remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Segment Any Gaussian Splatting SLAM
description: Segment Any Gaussian Splatting SLAM

## Links
- [Paper](https://github.com/narayanlongani/test.github.io)
- [GitHub Code](https://github.com/narayanlongani/test.github.io)
